#!/usr/bin/env python3
"""Render the hardening wrap-build Dockerfile for an imported image.

    wrap.py --from <repo>@<digest> --config image-config.json --labels labels.json --out Dockerfile

image-config.json is the output of `docker buildx imagetools inspect --format '{{json .Image}}'`,
either one image config or a map keyed by platform. The Dockerfile hardens the image, flattens it
to one layer, then re-emits the config the flatten dropped and bakes the labels in.
"""
import argparse
import json
import sys


def image_config(doc):
    if isinstance(doc, dict) and "config" in doc:
        return doc.get("config") or {}
    if isinstance(doc, dict):
        for _platform, img in sorted(doc.items()):
            if isinstance(img, dict) and "config" in img:
                return img.get("config") or {}
    raise SystemExit("wrap.py: no image config found in the inspect output")


def q(s):
    return '"' + str(s).replace("\\", "\\\\").replace('"', '\\"').replace("$", "\\$") + '"'


def render(src, cfg, labels):
    out = ["# syntax=docker/dockerfile:1.7",
           "# generated by supply-chain-lib hardenImage, do not edit",
           f"FROM {src} AS build",
           "USER 0",
           "COPY hardening/ /usr/local/lib/hardening/",
           "RUN sh /usr/local/lib/hardening/harden.sh",
           "",
           "FROM scratch",
           "COPY --from=build / /"]
    env = cfg.get("Env") or []
    if not any(e.startswith("PATH=") for e in env):
        out.append('ENV PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"')
    for e in env:
        k, _, v = e.partition("=")
        out.append(f"ENV {k}={q(v)}")
    if cfg.get("WorkingDir"):
        out.append(f"WORKDIR {cfg['WorkingDir']}")
    ports = sorted((cfg.get("ExposedPorts") or {}).keys())
    if ports:
        out.append("EXPOSE " + " ".join(ports))
    vols = sorted((cfg.get("Volumes") or {}).keys())
    if vols:
        out.append("VOLUME " + json.dumps(vols))
    if cfg.get("StopSignal"):
        out.append(f"STOPSIGNAL {cfg['StopSignal']}")
    if cfg.get("Entrypoint"):
        out.append("ENTRYPOINT " + json.dumps(cfg["Entrypoint"]))
    if cfg.get("Cmd"):
        out.append("CMD " + json.dumps(cfg["Cmd"]))
    user = cfg.get("User") or ""
    if not user or user in ("0", "root", "0:0", "root:root"):
        out.append("# WARNING: the source image runs as root; hardening keeps the original USER")
    out.append(f"USER {user or '0'}")
    for k in sorted(labels):
        out.append(f"LABEL {q(k)}={q(labels[k])}")
    return "\n".join(out) + "\n"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--from", dest="src", required=True)
    ap.add_argument("--config", required=True)
    ap.add_argument("--labels", required=True)
    ap.add_argument("--out", default="-")
    a = ap.parse_args()
    with open(a.config) as fh:
        cfg = image_config(json.load(fh))
    with open(a.labels) as fh:
        labels = json.load(fh)
    text = render(a.src, cfg, labels)
    if a.out == "-":
        sys.stdout.write(text)
    else:
        with open(a.out, "w") as fh:
            fh.write(text)


if __name__ == "__main__":
    main()
