package imagefactory.gate

import rego.v1

# Run: opa test resources/policy/
# Complete-input fixtures so the gate LOGIC is exercised before the external rules repo is wired.

_labels := {
	"org.opencontainers.image.base.digest": "sha256:abc",
	"org.opencontainers.image.base.name": "ubuntu:22.04",
	"org.opencontainers.image.created": "2026-07-07T00:00:00Z",
	"org.opencontainers.image.description": "x",
	"org.opencontainers.image.source": "https://git/x",
	"org.opencontainers.image.vendor": "Acme",
	"org.opencontainers.image.os": "ubuntu",
	"org.opencontainers.image.os.version": "22.04",
	"acme.container.governance.image.auid": "AP1",
	"acme.container.governance.image.category": "OS",
	"acme.container.security.ca-source": "internal-pki",
}

_release := {
	"target": "release", "kind": "os", "hardened": true, "labels": _labels,
	"scan": {"available": true, "criticalCount": 0, "highCount": 0},
	"sbomGenerated": true,
}

test_clean_release_allowed if {
	allow with input as _release
}

test_missing_label_denied if {
	count(deny) > 0 with input as json.remove(_release, ["labels/org.opencontainers.image.base.digest"])
}

test_nonhardened_release_denied if {
	deny["non-hardened image cannot be released"] with input as json.patch(_release, [{"op": "replace", "path": "/hardened", "value": false}])
}

test_vendor_nonhardened_allowed if {
	allow with input as json.patch(_release, [{"op": "replace", "path": "/hardened", "value": false}, {"op": "replace", "path": "/kind", "value": "vendor"}])
}

test_import_as_is_nonhardened_allowed if {
	allow with input as json.patch(_release, [{"op": "replace", "path": "/hardened", "value": false}, {"op": "replace", "path": "/kind", "value": "import"}, {"op": "add", "path": "/origin", "value": "vendor"}, {"op": "add", "path": "/importedAsIs", "value": true}])
}

test_import_not_as_is_nonhardened_denied if {
	deny["non-hardened image cannot be released"] with input as json.patch(_release, [{"op": "replace", "path": "/hardened", "value": false}, {"op": "replace", "path": "/kind", "value": "import"}, {"op": "add", "path": "/origin", "value": "internal"}, {"op": "add", "path": "/importedAsIs", "value": false}])
}

test_import_critical_blocks_release if {
	count(deny) > 0 with input as json.patch(_release, [{"op": "replace", "path": "/kind", "value": "import"}, {"op": "add", "path": "/origin", "value": "vendor"}, {"op": "add", "path": "/importedAsIs", "value": true}, {"op": "replace", "path": "/scan/criticalCount", "value": 1}])
}

test_missing_scan_fails_closed if {
	deny["release blocked: no completed vulnerability scan"] with input as json.patch(_release, [{"op": "replace", "path": "/scan/available", "value": false}])
}

test_critical_blocks_release if {
	count(deny) > 0 with input as json.patch(_release, [{"op": "replace", "path": "/scan/criticalCount", "value": 1}])
}

test_high_over_threshold_blocks_release if {
	count(deny) > 0 with input as json.patch(_release, [{"op": "replace", "path": "/scan/highCount", "value": 3}])
}

test_no_sbom_denied if {
	deny["release blocked: no SBOM generated by the scan step"] with input as json.patch(_release, [{"op": "replace", "path": "/sbomGenerated", "value": false}])
}

test_devca_blocked_from_release if {
	count(deny) > 0 with input as json.patch(_release, [{"op": "replace", "path": "/labels/acme.container.security.ca-source", "value": "dev-fake"}])
}

test_dev_target_only_needs_labels if {
	allow with input as {"target": "dev", "kind": "os", "hardened": false, "labels": _labels, "scan": {"available": false}, "sbomGenerated": false}
}

test_missing_os_labels_denied if {
	count(deny) > 0 with input as json.remove(_release, ["labels/org.opencontainers.image.os"])
	count(deny) > 0 with input as json.remove(_release, ["labels/org.opencontainers.image.os.version"])
}
