package imagefactory.gate

import rego.v1

# ============================================================================
# EXAMPLE policy the LOGIC lives here; the real, versioned rules (thresholds,
# per-CVE waivers, CTI scoring) live in a SEPARATE rules repo and are loaded by
# vars/gateImage from ${RULES_REPO_DIR} (falling back to this file, bundled as a library resource).
#
# Decision: `deny` is a set of reasons. Empty deny == pass. `allow` is convenience.
#
# Input shape (written by jenkins/vars/gateImage from the supply-chain record):
#   { "target": "dev" | "release",
#     "kind":   "os" | "runtime" | "debug" | "import",
#     "origin": "built" | "vendor" | "internal",
#     "importedAsIs": bool,     # true = the supply chain did NOT harden this image (import as-is)
#     "hardened": bool,
#     "labels": { "<label>": "<value>", ... },
#     "scan":   { "available": bool, "criticalCount": n, "highCount": n, "ctiScore": n },
#     "sbomGenerated": bool }
#
# NOTE: the gate runs BEFORE sign/attest (you can only sign a published digest), so it checks
# the SBOM was GENERATED not attested. Signature + SLSA/SBOM attestations are attached after
# promotion by secureImage and VERIFIED at deploy-time admission (see RUNBOOK).
# ============================================================================

default allow := false

allow if count(deny) == 0

# Tunable in the external rules repo.
threshold_high := 0

# Mandatory governance + OCI labels (container image governance sheet) all targets.
mandatory := {
	"org.opencontainers.image.base.digest",
	"org.opencontainers.image.base.name",
	"org.opencontainers.image.created",
	"org.opencontainers.image.description",
	"org.opencontainers.image.source",
	"org.opencontainers.image.vendor",
	"org.opencontainers.image.os",
	"org.opencontainers.image.os.version",
	"acme.container.governance.image.auid",
	"acme.container.governance.image.category",
}

deny contains msg if {
	some l in mandatory
	not input.labels[l]
	msg := sprintf("missing mandatory label: %s", [l])
}

# ---- release-only gates ----------------------------------------------------

# Only hardened images may be released EXCEPT images imported as-is (vendor images, and
# internal images whose spec opts out of hardening: their golden base's hardening is trusted).
# The external rules repo may tighten this per `origin`.
imported_as_is if input.importedAsIs == true

imported_as_is if input.kind == "vendor"   # legacy gate inputs (pre-record shape)

deny contains msg if {
	input.target == "release"
	not imported_as_is
	not input.hardened
	msg := "non-hardened image cannot be released"
}

# Fail CLOSED: a release requires a completed scan (missing report != 0 criticals).
deny contains msg if {
	input.target == "release"
	not input.scan.available
	msg := "release blocked: no completed vulnerability scan"
}

# Interim severity thresholds. The CVE verdict and the CTI score come from the Supply Chain API
# once gateImage calls it; these two rules stay as a floor until then.
deny contains msg if {
	input.target == "release"
	input.scan.criticalCount > 0
	msg := sprintf("release blocked: %d critical vulnerabilities", [input.scan.criticalCount])
}

deny contains msg if {
	input.target == "release"
	input.scan.highCount > threshold_high
	msg := sprintf("release blocked: %d high vulnerabilities (> %d)", [input.scan.highCount, threshold_high])
}

# An SBOM must have been GENERATED by the scan step before release. (Signature + SLSA/SBOM
# attestations are attached AFTER promotion by secureImage and verified at deploy admission.)
deny contains msg if {
	input.target == "release"
	not input.sbomGenerated
	msg := "release blocked: no SBOM generated by the scan step"
}

# The DEV / fake internal CA must never reach release.
deny contains msg if {
	input.target == "release"
	input.labels["acme.container.security.ca-source"] == "dev-fake"
	msg := "release blocked: image trusts the DEV/fake CA"
}
